
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;

namespace HealthCheck_ConsoleApp
{
    class Program
    {
        static void Main()
        {
        }
    }
}
