
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;

namespace HealthCheck_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var _dataset = System.IO.File.ReadAllLines("dataset.csv"); ;
            var input = "headaches, sore_throat, restlessness, nasal_discharge, body_aches".Replace(" ", "").Split(',');
            var output = HealthCheck.SecondPrediction(input, _dataset);
            Console.ReadKey();
        }
    }
}
