
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace HealthCheck_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            HealthCheck.ModelInput sampleData = new HealthCheck.ModelInput()
            {
                Col1 = @"itching",
                Col2 = @"skin_rash",
                Col3 = @"nodal_skin_eruptions",
                Col4 = @"dischromic _patches",
                Col5 = @"",
                Col6 = @"",
                Col7 = @"",
                Col8 = @"",
                Col9 = @"",
                Col10 = @"",
                Col11 = @"",
                Col12 = @"",
                Col13 = @"",
                Col14 = @"",
                Col15 = @"",
                Col16 = @"",
                Col17 = @"",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = HealthCheck.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");


            Console.WriteLine($"Col0: {@"Fungal infection"}");
            Console.WriteLine($"Col1: {@"itching"}");
            Console.WriteLine($"Col2: {@"skin_rash"}");
            Console.WriteLine($"Col3: {@"nodal_skin_eruptions"}");
            Console.WriteLine($"Col4: {@"dischromic _patches"}");
            Console.WriteLine($"Col5: {@""}");
            Console.WriteLine($"Col6: {@""}");
            Console.WriteLine($"Col7: {@""}");
            Console.WriteLine($"Col8: {@""}");
            Console.WriteLine($"Col9: {@""}");
            Console.WriteLine($"Col10: {@""}");
            Console.WriteLine($"Col11: {@""}");
            Console.WriteLine($"Col12: {@""}");
            Console.WriteLine($"Col13: {@""}");
            Console.WriteLine($"Col14: {@""}");
            Console.WriteLine($"Col15: {@""}");
            Console.WriteLine($"Col16: {@""}");
            Console.WriteLine($"Col17: {@""}");


            Console.WriteLine($"\n\nPredicted Col0: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
